services:
  # Cloud DBeaver
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - 8978:8978
    extra_hosts:
      - host.docker.internal:host-gateway
